# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ii9xNqoseAHla9BckY4Bm0oJxNMWMFqBSsAEz/1zDuLC5GDzraT4PBUGocBtaIBSQWoGJC23PBeTAri+olmT5Hk862rB0U53dpP/1yMrWP0vG4y005LCSB/pP3bS0AvQoyfeEuEQ0/wduziqhjREb8ec1BDU2hyOecpZvj2c2MfuTwJAeTtQPQu4EXWqxHUgpb5vH2Wjqaa6xtlNRnoyEeZ3aaAXzLGjmALxQQ3v8uUYEJHDJCp0Qw37HfySDO2FDZ5rF7Y8HPTWBZTgrj/d5AoZ/Ay7Zf9c3OF6eGolpobMswjRJ1LPpKjSLXS3mRCJp6cqCWZfvkjsJyFquRCufR2mozWrOmZbScO9v16d1FKA0G3b5YK5Fqk89YBs0Csv3R1MxMynGXDAh/U/ItEOOPkxBKN2FyLgHMX8QgRMjb0QbLOKrUkT4Ttkox6/mhYiEMVwuDzPOuD2HtcQApvmZ9Muh28R8NX3pvPgPeFeKmJ1hnSSe5B1adi2+sKmKCrpr8pr2lIDvb5aYqLWMpBzQ9Uzg1dJ2VtDtswX5rsU9UkUolG81cnOfuuyaWambWb1SjKmlDhvRcbgR0aZn10jwSivfvf+RYT2RIpqRCYrxa0RKUC5Z2OoXFOI+os07D9OsS7WM6evB4jiBONoKwdPxG2EgOiceuhODWMDopAIFnE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
