travis:
  secure:
    BINSTAR_TOKEN: Ii9xNqoseAHla9BckY4Bm0oJxNMWMFqBSsAEz/1zDuLC5GDzraT4PBUGocBtaIBSQWoGJC23PBeTAri+olmT5Hk862rB0U53dpP/1yMrWP0vG4y005LCSB/pP3bS0AvQoyfeEuEQ0/wduziqhjREb8ec1BDU2hyOecpZvj2c2MfuTwJAeTtQPQu4EXWqxHUgpb5vH2Wjqaa6xtlNRnoyEeZ3aaAXzLGjmALxQQ3v8uUYEJHDJCp0Qw37HfySDO2FDZ5rF7Y8HPTWBZTgrj/d5AoZ/Ay7Zf9c3OF6eGolpobMswjRJ1LPpKjSLXS3mRCJp6cqCWZfvkjsJyFquRCufR2mozWrOmZbScO9v16d1FKA0G3b5YK5Fqk89YBs0Csv3R1MxMynGXDAh/U/ItEOOPkxBKN2FyLgHMX8QgRMjb0QbLOKrUkT4Ttkox6/mhYiEMVwuDzPOuD2HtcQApvmZ9Muh28R8NX3pvPgPeFeKmJ1hnSSe5B1adi2+sKmKCrpr8pr2lIDvb5aYqLWMpBzQ9Uzg1dJ2VtDtswX5rsU9UkUolG81cnOfuuyaWambWb1SjKmlDhvRcbgR0aZn10jwSivfvf+RYT2RIpqRCYrxa0RKUC5Z2OoXFOI+os07D9OsS7WM6evB4jiBONoKwdPxG2EgOiceuhODWMDopAIFnE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
