travis:
  secure:
    BINSTAR_TOKEN: q5UzdzUH05ltfXtbIH0q1uQkhLgWt0gd7bYc1I1RwT4et47d+NF2XYuiMkGN70hVd7iiMlBd+m1egp5DGGIX41U0XVb7Js3m5LVn+7lV0pjtLem/qdn8wgOJqN/RfAIUKGbx5cM7MZA1Agzym7psaOVBJXcwqOyaCS9rLBgIRL8BAUaUPXYa6Rk8gHbH+LIc20ROaViEoAOQWAOHOOgNZMwTAmC/QB4X3nSfCnYh9CEvTTnz3mUo/bKDt0fGoFc3eKriN/INAfmp9ZhJIAsLeaq15GJTlDNB423mDj2iUHGXYS0i8Aqh3Fp4KavjOfkZdcp8iV8WoGn/G8cQw/aPG96gqNLPOEAa0rgN0t3QJw7m+saxWAiXEWeZZGmJdlJz49RIBkrdtY1UwgGwCWCDY6lCNf9LB2PPaoBuP3yPZCUkAvEAWn5h38W5JgdyfO0UKKmvNayXHIRYPCtwx0qrsidbAWtF4ps/g16E9Z3CEIbsi5WVCiW0uxudcg8JUsvQu5lZLrfXKrZ1BQhv2ATWO7LG6QRVw3fBZU7aYsKyC02D0bsolYimVsG7urXnke9HRCEmF/z485sP009sKr5Z/bl7r/QFlpI9PHKbLviMcPW7d/18jq3sJQuRQn9YW4oEYAHfb8Hd4yjya/9nFPH7Ca8IYLkz17NtykLRVCrfXmE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
